# Generated by Django 4.1.3 on 2022-12-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehiclesImages',
        ),
    ]
