# Generated by Django 4.1.3 on 2022-12-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_delete_vehiclesimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='brand',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VehiclesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
        ),
    ]
